version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install time
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file package.yml
artifacts:
  type: zip
  files:
    - template.yml
    - package.yml